name: Update CNAME records

on:
  pull_request:
    types: [closed]

jobs:
  update-cname:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install requests

      - name: Verify secrets (for debug)
        run: |
          echo "CF_ZONE_ID=${{ secrets.CF_ZONE_ID }}"
          echo "CF_API_TOKEN=${{ secrets.CF_API_TOKEN }}"

      - name: Update CNAME records in Cloudflare
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        run: |
          python update_cname.py


      - name: Upload log file
        uses: actions/upload-artifact@v3
        with:
          name: dns-update-logs
          path: dns_update_log.txt
